[phases.setup]
    nixPkgs = ['nodejs', 'python3']
    aptPkgs = ['build-essential', 'libudev-dev']

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "pnpm run pm2"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10